allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260908.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260908.1'
  - '@cloudflare/workerd-linux-64@1.20260908.1'
  - '@cloudflare/workerd-linux-arm64@1.20260908.1'
  - '@cloudflare/workerd-windows-64@1.20260908.1'
  - '@cloudflare/workers-types@5.20260908.1'
  - miniflare@5.20260908.0-alpha
  - workerd@1.20260908.1
  - wrangler@4.130.0
  - '@cloudflare/vitest-plugin@1.1.6'
