import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const luaPath = resolve(projectRoot, "twenty.lua");
const sourcePath = resolve(projectRoot, "src", "index.ts");
const generatedModulePath = resolve(projectRoot, "src", "lua-source.generated.ts");
const outputPath = resolve(projectRoot, "dist", "worker.mjs");

const [luaSource, workerSource] = await Promise.all([
  readFile(luaPath, "utf8"),
  readFile(sourcePath, "utf8"),
]);

const importPattern = /^import luaSource from "\.\/lua-source\.generated";\r?\n/;
if (!importPattern.test(workerSource)) {
  throw new Error("Expected Lua source import was not found in src/index.ts");
}

const combinedSource = workerSource.replace(
  importPattern,
  `const luaSource = ${JSON.stringify(luaSource)};\n`,
);
const result = ts.transpileModule(combinedSource, {
  compilerOptions: {
    module: ts.ModuleKind.ESNext,
    target: ts.ScriptTarget.ES2023,
  },
  fileName: "worker.ts",
  reportDiagnostics: true,
});

const errors = (result.diagnostics ?? []).filter(
  (diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error,
);
if (errors.length > 0) {
  throw new Error(
    errors.map((diagnostic) => ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n")).join("\n"),
  );
}

await Promise.all([
  mkdir(dirname(generatedModulePath), { recursive: true }),
  mkdir(dirname(outputPath), { recursive: true }),
]);
await Promise.all([
  writeFile(
    generatedModulePath,
    `// Generated from twenty.lua. Do not edit this file directly.\nexport default ${JSON.stringify(luaSource)};\n`,
    "utf8",
  ),
  writeFile(outputPath, result.outputText, "utf8"),
]);
